// 关键词手绘配图清单：term -> 配图公开路径。
// 配图按关键词文案（term）索引，与数据库随机 id 解耦——重新 seed 不会再失配。
// 现有 100 张图对应「人工智能（普及版）」5 章 100 词，按创建顺序与图片一一对齐恢复而来。
// 新增配图：把图片放进 public/keyword-illustrations/，并在此登记 term -> 路径。

export const ILLUSTRATION_BY_TERM: Record<string, string> = {
  "人工智能(AI)": "/keyword-illustrations/cmq3issno000ctnufu3eds04o.png",
  "图灵测试(Turing Test)": "/keyword-illustrations/cmq3issno000dtnufqeqm96ko.png",
  "机器学习(Machine Learning)": "/keyword-illustrations/cmq3issno000etnufj752bwe5.png",
  "深度学习(Deep Learning)": "/keyword-illustrations/cmq3issno000ftnufbfchuivm.png",
  "神经网络(Neural Network)": "/keyword-illustrations/cmq3issno000gtnufxzvat62i.png",
  "算法(Algorithm)": "/keyword-illustrations/cmq3issno000htnufr2caipk6.png",
  "数据(Data)": "/keyword-illustrations/cmq3issno000itnufvco2ogi3.png",
  "算力(Computing Power)": "/keyword-illustrations/cmq3issno000jtnuf6jxooxwp.png",
  "模型(Model)": "/keyword-illustrations/cmq3issno000ktnuf6gxlkzqv.png",
  "训练与推理(Training & Inference)": "/keyword-illustrations/cmq3issno000ltnuf4fwwny07.png",
  "符号主义 vs 连接主义(Symbolism vs Connectionism)": "/keyword-illustrations/cmq3issno000mtnufmt1ffdes.png",
  "专家系统(Expert System)": "/keyword-illustrations/cmq3issno000ntnufva6ajax4.png",
  "AI 的浪潮与寒冬(AI Booms & Winters)": "/keyword-illustrations/cmq3issno000otnufcco4kps5.png",
  "弱人工智能 vs 强人工智能(Weak AI vs Strong AI)": "/keyword-illustrations/cmq3issno000ptnuf4yxsupsi.png",
  "通用人工智能(AGI)": "/keyword-illustrations/cmq3issno000qtnufzc1xtzo0.png",
  "大数据(Big Data)": "/keyword-illustrations/cmq3issno000rtnufl6029627.png",
  "云计算(Cloud Computing)": "/keyword-illustrations/cmq3issno000stnuf5jh0fjcs.png",
  "GPU 与 AI 芯片(GPU & AI Chips)": "/keyword-illustrations/cmq3issno000ttnufa9gn76ql.png",
  "开源与闭源模型(Open-Source vs Closed-Source Models)": "/keyword-illustrations/cmq3issno000utnuf050jt7bo.png",
  "AI 与自动化的区别(AI vs Automation)": "/keyword-illustrations/cmq3issno000vtnufrh4f2usk.png",
  "监督学习(Supervised Learning)": "/keyword-illustrations/cmq3issnv000xtnufk2hvyjmk.png",
  "无监督学习(Unsupervised Learning)": "/keyword-illustrations/cmq3issnv000ytnuf65sqbuu6.png",
  "强化学习(Reinforcement Learning)": "/keyword-illustrations/cmq3issnv000ztnuf68jxtpdl.png",
  "分类(Classification)": "/keyword-illustrations/cmq3issnv0010tnuf75191aak.png",
  "回归/预测(Regression)": "/keyword-illustrations/cmq3issnv0011tnufq5jxtb6x.png",
  "聚类(Clustering)": "/keyword-illustrations/cmq3issnv0012tnuf6fpo9c0n.png",
  "推荐系统(Recommender System)": "/keyword-illustrations/cmq3issnv0013tnufxsbepyvp.png",
  "特征(Feature)": "/keyword-illustrations/cmq3issnv0014tnufg2o59ysv.png",
  "数据标注(Data Labeling)": "/keyword-illustrations/cmq3issnv0015tnuf3n2z02bc.png",
  "训练集与测试集(Training & Test Sets)": "/keyword-illustrations/cmq3issnv0016tnufc2ceiq9s.png",
  "过拟合(Overfitting)": "/keyword-illustrations/cmq3issnv0017tnuf5ple690a.png",
  "准确率(Accuracy)": "/keyword-illustrations/cmq3issnv0018tnufym7luov9.png",
  "数据质量(Data Quality)": "/keyword-illustrations/cmq3issnv0019tnufqhibnh8p.png",
  "数据偏见(Data Bias)": "/keyword-illustrations/cmq3issnv001atnufr4lo5pdp.png",
  "泛化(Generalization)": "/keyword-illustrations/cmq3issnv001btnufka08d1fe.png",
  "模式识别(Pattern Recognition)": "/keyword-illustrations/cmq3issnv001ctnufh3l4mzhn.png",
  "预测分析(Predictive Analytics)": "/keyword-illustrations/cmq3issnv001dtnufitsaligd.png",
  "异常检测(Anomaly Detection)": "/keyword-illustrations/cmq3issnv001etnufcyqijwxk.png",
  "机器学习能做什么(What Machine Learning Can Do)": "/keyword-illustrations/cmq3issnv001ftnufelkymrq8.png",
  "机器学习的局限(Limits of Machine Learning)": "/keyword-illustrations/cmq3issnv001gtnufqrvf9944.png",
  "计算机视觉(Computer Vision)": "/keyword-illustrations/cmq3isso2001itnufk7h8a99d.png",
  "世界模型(World Model)": "/keyword-illustrations/cmq3isso2001jtnufp58g8m32.png",
  "人脸识别(Face Recognition)": "/keyword-illustrations/cmq3isso2001ktnuf8ckk7d0w.png",
  "语音识别(Speech Recognition)": "/keyword-illustrations/cmq3isso2001ltnufdzofpxmp.png",
  "语音合成(Speech Synthesis / TTS)": "/keyword-illustrations/cmq3isso2001mtnufiqy8z9zs.png",
  "自然语言处理(NLP)": "/keyword-illustrations/cmq3isso2001ntnufh61o106z.png",
  "机器翻译(Machine Translation)": "/keyword-illustrations/cmq3isso2001otnuff9gc0ghs.png",
  "OCR 文字识别(Optical Character Recognition)": "/keyword-illustrations/cmq3isso2001ptnufs599rz2q.png",
  "语义理解(Semantic Understanding)": "/keyword-illustrations/cmq3isso2001qtnufxuhpeawg.png",
  "生成对抗网络(GAN)": "/keyword-illustrations/cmq3isso2001rtnuf3uewuv3x.png",
  "扩散模型(Diffusion Model)": "/keyword-illustrations/cmq3isso2001stnufqyw4a81b.png",
  "多模态(Multimodal)": "/keyword-illustrations/cmq3isso2001ttnufjciyfy5o.png",
  "图像生成(Image Generation)": "/keyword-illustrations/cmq3isso2001utnufttqtyahi.png",
  "视频生成(Video Generation)": "/keyword-illustrations/cmq3isso2001vtnufsr3wmcww.png",
  "数字人(Digital Human)": "/keyword-illustrations/cmq3isso2001wtnufdh811a6l.png",
  "自动驾驶(Autonomous Driving)": "/keyword-illustrations/cmq3isso2001xtnufe3i6e4b3.png",
  "具身智能/机器人(Embodied AI / Robotics)": "/keyword-illustrations/cmq3isso2001ytnufwz1c823g.png",
  "时间序列(Time Series)": "/keyword-illustrations/cmq3isso2001ztnuf4g8jtkuh.png",
  "风险预测(Risk Prediction)": "/keyword-illustrations/cmq3isso20020tnuf93b0tlos.png",
  "深度学习改变了什么(What Deep Learning Changed)": "/keyword-illustrations/cmq3isso20021tnufexowv0nj.png",
  "大语言模型(LLM)": "/keyword-illustrations/cmq3isso80023tnufkcqmbr5p.png",
  "ChatGPT": "/keyword-illustrations/cmq3isso80024tnuf7fs4d2jn.png",
  "国产大模型(豆包/DeepSeek/通义/文心)": "/keyword-illustrations/cmq3isso80025tnufcjkvy7ra.png",
  "Transformer": "/keyword-illustrations/cmq3isso80026tnufy91drtry.png",
  "生成式 AI(AIGC)": "/keyword-illustrations/cmq3isso80027tnufnv2fagme.png",
  "预训练(Pre-training)": "/keyword-illustrations/cmq3isso80028tnufah3iri4l.png",
  "微调(Fine-tuning)": "/keyword-illustrations/cmq3isso80029tnufh63ynd7w.png",
  "提示词(Prompt)": "/keyword-illustrations/cmq3isso8002atnufmxfq0imw.png",
  "上下文窗口(Context Window)": "/keyword-illustrations/cmq3isso8002btnufcx488991.png",
  "Token": "/keyword-illustrations/cmq3isso8002ctnufiugs2e70.png",
  "思维链(CoT)": "/keyword-illustrations/cmq3isso8002dtnufe7f4avps.png",
  "推理大模型(o1/DeepSeek-R1)": "/keyword-illustrations/cmq3isso8002etnuf5aqw6czo.png",
  "涌现能力(Emergent Abilities)": "/keyword-illustrations/cmq3isso8002ftnufcz7b4u81.png",
  "大模型幻觉(Hallucination)": "/keyword-illustrations/cmq3isso8002gtnufr8r8g4or.png",
  "知识截止日期(Knowledge Cutoff)": "/keyword-illustrations/cmq3isso8002htnufnec12ddp.png",
  "多模态大模型(Multimodal LLM)": "/keyword-illustrations/cmq3isso8002itnuf34mvdpsv.png",
  "大模型评测/排行榜(LLM Benchmarks)": "/keyword-illustrations/cmq3isso8002jtnufv9amvgrw.png",
  "大模型的成本(Cost of LLMs)": "/keyword-illustrations/cmq3isso8002ktnufajdke7he.png",
  "大模型能做什么(What LLMs Can Do)": "/keyword-illustrations/cmq3isso8002ltnuff0v5is5u.png",
  "大模型不能做什么(What LLMs Cannot Do)": "/keyword-illustrations/cmq3isso8002mtnufax0erp51.png",
  "AI 智能体(Agent)": "/keyword-illustrations/cmq3issoe002otnuf96wjo3m1.png",
  "AI 副驾驶(Copilot)": "/keyword-illustrations/cmq3issoe002ptnuf1mssp240.png",
  "检索增强(RAG)": "/keyword-illustrations/cmq3issoe002qtnuffw7l07f8.png",
  "企业知识库问答(Enterprise Knowledge Base QA)": "/keyword-illustrations/cmq3issoe002rtnufqjsxtwlr.png",
  "工具调用(Tool Use)": "/keyword-illustrations/cmq3issoe002stnufqy8h18hu.png",
  "知识图谱(Knowledge Graph)": "/keyword-illustrations/cmq3issoe002ttnufrjgs3z63.png",
  "数字孪生(Digital Twin)": "/keyword-illustrations/cmq3issoe002utnufvofzw8zt.png",
  "AI 辅助诊断(AI-Assisted Diagnosis，辅助非替代)": "/keyword-illustrations/cmq3issoe002vtnufa64bwyib.png",
  "AI 在医疗健康(AI in Healthcare)": "/keyword-illustrations/cmq3issoe002wtnufaxsel6tk.png",
  "AI 私有化部署(On-Premise / Private Deployment)": "/keyword-illustrations/cmq3issoe002xtnufzrz0jo24.png",
  "边缘 AI(Edge AI)": "/keyword-illustrations/cmq3issoe002ytnufp209w1if.png",
  "AI 落地的难点(Challenges of AI Adoption)": "/keyword-illustrations/cmq3issoe002ztnufsxb13pj6.png",
  "数据隐私(Data Privacy)": "/keyword-illustrations/cmq3issoe0030tnuf7bv2l6qn.png",
  "AI 安全(AI Safety)": "/keyword-illustrations/cmq3issoe0031tnufmguowcj1.png",
  "深度伪造(Deepfake)": "/keyword-illustrations/cmq3issoe0032tnufubislgnb.png",
  "AI 偏见与公平(AI Bias & Fairness)": "/keyword-illustrations/cmq3issoe0033tnufld0kszfg.png",
  "AI 治理与监管(AI Governance & Regulation)": "/keyword-illustrations/cmq3issoe0034tnufsp689g5w.png",
  "AI 伦理(AI Ethics)": "/keyword-illustrations/cmq3issoe0035tnufo2bg789k.png",
  "AI 对工作的影响(AI's Impact on Jobs)": "/keyword-illustrations/cmq3issoe0036tnuf58skz28i.png",
  "AI 的未来趋势(Future Trends of AI)": "/keyword-illustrations/cmq3issoe0037tnufau390y6i.png",
  "图灵机(Turing Machine)": "/keyword-illustrations/pro-ch1-01.png",
  "人工智能(Artificial Intelligence)": "/keyword-illustrations/pro-ch1-02.png",
  "达特茅斯会议(Dartmouth Conference)": "/keyword-illustrations/pro-ch1-03.png",
  "符号主义(Symbolicism)": "/keyword-illustrations/pro-ch1-04.png",
  "连接主义(Connectionism)": "/keyword-illustrations/pro-ch1-05.png",
  "知识表示(Knowledge Representation)": "/keyword-illustrations/pro-ch1-06.png",
  "逻辑推理(Logical Reasoning)": "/keyword-illustrations/pro-ch1-07.png",
  "搜索算法(Search Algorithm)": "/keyword-illustrations/pro-ch1-08.png",
  "启发式搜索(Heuristic Search)": "/keyword-illustrations/pro-ch1-09.png",
  "感知机(Perceptron)": "/keyword-illustrations/pro-ch1-10.png",
  "AI寒冬(AI Winter)": "/keyword-illustrations/pro-ch1-11.png",
  "计算复杂度(Computational Complexity)": "/keyword-illustrations/pro-ch1-12.png",
  "概率论(Probability Theory)": "/keyword-illustrations/pro-ch1-13.png",
  "贝叶斯定理(Bayes' Theorem)": "/keyword-illustrations/pro-ch1-14.png",
  "统计推断(Statistical Inference)": "/keyword-illustrations/pro-ch1-15.png",
  "线性代数(Linear Algebra)": "/keyword-illustrations/pro-ch1-16.png",
  "微积分与最优化基础(Calculus and Optimization)": "/keyword-illustrations/pro-ch1-17.png",
  "信息论(Information Theory)": "/keyword-illustrations/pro-ch1-18.png",
  "回归分析(Regression)": "/keyword-illustrations/pro-ch2-01.png",
  "决策树(Decision Tree)": "/keyword-illustrations/pro-ch2-02.png",
  "随机森林(Random Forest)": "/keyword-illustrations/pro-ch2-03.png",
  "支持向量机(Support Vector Machine)": "/keyword-illustrations/pro-ch2-04.png",
  "K近邻算法(K-Nearest Neighbors)": "/keyword-illustrations/pro-ch2-05.png",
  "朴素贝叶斯(Naive Bayes)": "/keyword-illustrations/pro-ch2-06.png",
  "集成学习(Ensemble Learning)": "/keyword-illustrations/pro-ch2-07.png",
  "梯度提升(Gradient Boosting)": "/keyword-illustrations/pro-ch2-08.png",
  "特征工程(Feature Engineering)": "/keyword-illustrations/pro-ch2-09.png",
  "降维(Dimensionality Reduction)": "/keyword-illustrations/pro-ch2-10.png",
  "偏差-方差权衡(Bias-Variance Tradeoff)": "/keyword-illustrations/pro-ch2-11.png",
  "过拟合与欠拟合(Overfitting and Underfitting)": "/keyword-illustrations/pro-ch2-12.png",
  "正则化(Regularization)": "/keyword-illustrations/pro-ch2-13.png",
  "交叉验证(Cross-Validation)": "/keyword-illustrations/pro-ch2-14.png",
  "人工神经网络(Artificial Neural Network)": "/keyword-illustrations/pro-ch3-01.png",
  "反向传播(Backpropagation)": "/keyword-illustrations/pro-ch3-02.png",
  "损失函数(Loss Function)": "/keyword-illustrations/pro-ch3-03.png",
  "激活函数(Activation Function)": "/keyword-illustrations/pro-ch3-04.png",
  "梯度下降(Gradient Descent)": "/keyword-illustrations/pro-ch3-05.png",
  "自监督学习(Self-Supervised Learning)": "/keyword-illustrations/pro-ch3-06.png",
  "卷积神经网络(Convolutional Neural Network)": "/keyword-illustrations/pro-ch3-07.png",
  "池化(Pooling)": "/keyword-illustrations/pro-ch3-08.png",
  "批归一化(Batch Normalization)": "/keyword-illustrations/pro-ch3-09.png",
  "Dropout正则化(Dropout)": "/keyword-illustrations/pro-ch3-10.png",
  "梯度消失与梯度爆炸(Vanishing and Exploding Gradient)": "/keyword-illustrations/pro-ch3-11.png",
  "残差网络(ResNet)": "/keyword-illustrations/pro-ch3-12.png",
  "循环神经网络(Recurrent Neural Network)": "/keyword-illustrations/pro-ch3-13.png",
  "长短期记忆网络(LSTM)": "/keyword-illustrations/pro-ch3-14.png",
  "自编码器(Autoencoder)": "/keyword-illustrations/pro-ch3-15.png",
  "词嵌入(Word Embedding)": "/keyword-illustrations/pro-ch3-16.png",
  "迁移学习(Transfer Learning)": "/keyword-illustrations/pro-ch3-17.png",
  "注意力机制(Attention)": "/keyword-illustrations/pro-ch4-01.png",
  "自注意力(Self-Attention)": "/keyword-illustrations/pro-ch4-02.png",
  "Transformer架构(Transformer)": "/keyword-illustrations/pro-ch4-03.png",
  "大语言模型(Large Language Model)": "/keyword-illustrations/pro-ch4-04.png",
  "GPT系列(GPT)": "/keyword-illustrations/pro-ch4-05.png",
  "BERT模型(BERT)": "/keyword-illustrations/pro-ch4-06.png",
  "参数高效微调(PEFT/LoRA)": "/keyword-illustrations/pro-ch4-07.png",
  "上下文学习(In-Context Learning)": "/keyword-illustrations/pro-ch4-08.png",
  "思维链(Chain-of-Thought)": "/keyword-illustrations/pro-ch4-09.png",
  "推理模型与测试时计算(Reasoning Models / Test-Time Compute, o1/o3)": "/keyword-illustrations/pro-ch4-10.png",
  "人类反馈强化学习(RLHF)": "/keyword-illustrations/pro-ch4-11.png",
  "直接偏好优化(Direct Preference Optimization, DPO)": "/keyword-illustrations/pro-ch4-12.png",
  "混合专家模型(Mixture of Experts, MoE)": "/keyword-illustrations/pro-ch4-13.png",
  "嵌入与表征学习(Embeddings & Representation Learning)": "/keyword-illustrations/pro-ch4-14.png",
  "长上下文(Long Context)": "/keyword-illustrations/pro-ch4-15.png",
  "缩放定律(Scaling Law)": "/keyword-illustrations/pro-ch4-16.png",
  "Token与分词(Tokenization)": "/keyword-illustrations/pro-ch4-17.png",
  "检索增强生成(Retrieval-Augmented Generation, RAG)": "/keyword-illustrations/pro-ch5-01.png",
  "向量数据库(Vector Database)": "/keyword-illustrations/pro-ch5-02.png",
  "知识图谱与GraphRAG(Knowledge Graph / GraphRAG)": "/keyword-illustrations/pro-ch5-03.png",
  "提示工程与上下文工程(Prompt & Context Engineering)": "/keyword-illustrations/pro-ch5-04.png",
  "AI智能体(AI Agent)": "/keyword-illustrations/pro-ch5-05.png",
  "工具调用与函数调用(Tool Use / Function Calling)": "/keyword-illustrations/pro-ch5-06.png",
  "多智能体与编排/工作流(Multi-Agent Orchestration & Workflow)": "/keyword-illustrations/pro-ch5-07.png",
  "智能体记忆与规划(Agent Memory & Planning, ReAct)": "/keyword-illustrations/pro-ch5-08.png",
  "智能体互联协议(MCP / A2A)": "/keyword-illustrations/pro-ch5-09.png",
  "私有化与本地化部署(On-Premise / Private Deployment)": "/keyword-illustrations/pro-ch5-10.png",
  "推理优化与服务框架(Inference Serving: 蒸馏/量化 + vLLM/Xinference)": "/keyword-illustrations/pro-ch5-11.png",
  "LLM 评估与可观测(Evals & Observability)": "/keyword-illustrations/pro-ch5-12.png",
  "大模型网关(LLM Gateway)": "/keyword-illustrations/pro-ch5-13.png",
  "边缘AI与算力芯片(Edge AI and AI Chips)": "/keyword-illustrations/pro-ch5-14.png",
  "多模态融合(Multimodal Fusion)": "/keyword-illustrations/pro-ch5-15.png",
  "(ECG/信号)基础模型与时序风险预测(Signal Foundation Model · Time-LLM · Survival)": "/keyword-illustrations/pro-ch5-16.png",
  "医疗AI与临床决策支持(Medical AI / CDSS)": "/keyword-illustrations/pro-ch5-17.png",
  "大模型幻觉、护栏与可信落地(Hallucination · Guardrails · Human-in-the-loop)": "/keyword-illustrations/pro-ch5-18.png",
  "数据隐私、合规与AI治理(Data Privacy, Compliance & Governance)": "/keyword-illustrations/pro-ch5-19.png",
  "高频QRS(HFQRS)": "/keyword-illustrations/hfqrs-ch1-01.png",
  "常规心电图(Conventional ECG)": "/keyword-illustrations/hfqrs-ch1-02.png",
  "微伏级信号(Microvolt-level Signal)": "/keyword-illustrations/hfqrs-ch1-03.png",
  "心肌除极(Myocardial Depolarization)": "/keyword-illustrations/hfqrs-ch1-04.png",
  "心肌复极(Repolarization)": "/keyword-illustrations/hfqrs-ch1-05.png",
  "心肌缺血(Myocardial Ischemia)": "/keyword-illustrations/hfqrs-ch1-06.png",
  "缺血性心脏病(Ischemic Heart Disease, IHD)": "/keyword-illustrations/hfqrs-ch1-07.png",
  "浦肯野纤维系统(Purkinje Fiber System)": "/keyword-illustrations/hfqrs-ch1-08.png",
  "心肌激活位点(Myocardial Activation Site)": "/keyword-illustrations/hfqrs-ch1-09.png",
  "除极波阵(Depolarization Wavefront)": "/keyword-illustrations/hfqrs-ch1-10.png",
  "高频心电图(High-Frequency ECG, HFECG)": "/keyword-illustrations/hfqrs-ch1-11.png",
  "ATP能量代谢(ATP Energy Metabolism)": "/keyword-illustrations/hfqrs-ch1-12.png",
  "钠离子传导(Sodium Ion Conduction)": "/keyword-illustrations/hfqrs-ch1-13.png",
  "动作电位0相(Phase 0 of Action Potential)": "/keyword-illustrations/hfqrs-ch1-14.png",
  "跨壁传导(Transmural Conduction)": "/keyword-illustrations/hfqrs-ch1-15.png",
  "传导速度(Conduction Velocity)": "/keyword-illustrations/hfqrs-ch1-16.png",
  "高频成分衰减(High-frequency Attenuation)": "/keyword-illustrations/hfqrs-ch1-17.png",
  "心电信号碎裂(Fragmented QRS)": "/keyword-illustrations/hfqrs-ch1-18.png",
  "QRS复合体(QRS Complex)": "/keyword-illustrations/hfqrs-ch1-19.png",
  "缺血级联(Ischemic Cascade)": "/keyword-illustrations/hfqrs-ch1-20.png",
  "150–250Hz高频频带(High-frequency Band 150–250 Hz)": "/keyword-illustrations/hfqrs-ch2-01.png",
  "信号平均(Signal Averaging)": "/keyword-illustrations/hfqrs-ch2-02.png",
  "带通数字滤波器(Band-pass Digital Filter)": "/keyword-illustrations/hfqrs-ch2-03.png",
  "QRS对齐(QRS Alignment)": "/keyword-illustrations/hfqrs-ch2-04.png",
  "时域包络线(Time-domain Envelope)": "/keyword-illustrations/hfqrs-ch2-05.png",
  "信噪比(Signal-to-Noise Ratio, SNR)": "/keyword-illustrations/hfqrs-ch2-06.png",
  "均方根值(Root Mean Square, RMS)": "/keyword-illustrations/hfqrs-ch2-07.png",
  "振幅下降区(Reduced Amplitude Zone, RAZ)": "/keyword-illustrations/hfqrs-ch2-08.png",
  "信号平均心电图(Signal-Averaged ECG, SAECG)": "/keyword-illustrations/hfqrs-ch2-09.png",
  "信号降噪(Signal Noise Reduction)": "/keyword-illustrations/hfqrs-ch2-10.png",
  "QRS起止点检测(QRS Onset/Offset Detection)": "/keyword-illustrations/hfqrs-ch2-11.png",
  "12导联同步采集(12-lead Synchronous Acquisition)": "/keyword-illustrations/hfqrs-ch2-12.png",
  "连续小波变换(Continuous Wavelet Transform, CWT)": "/keyword-illustrations/hfqrs-ch2-13.png",
  "异常心搏剔除(Ectopic/Abnormal Beat Rejection)": "/keyword-illustrations/hfqrs-ch2-14.png",
  "运动噪声校正(Motion Artifact Correction)": "/keyword-illustrations/hfqrs-ch2-15.png",
  "基线漂移校正(Baseline Drift Correction)": "/keyword-illustrations/hfqrs-ch2-16.png",
  "高频形态指数(High-Frequency Morphology Index, HFMI)": "/keyword-illustrations/hfqrs-ch2-17.png",
  "QRS斜率分析(QRS Slope Analysis)": "/keyword-illustrations/hfqrs-ch2-18.png",
  "信号重构(Signal Reconstruction)": "/keyword-illustrations/hfqrs-ch2-19.png",
  "实时处理(Real-time Processing)": "/keyword-illustrations/hfqrs-ch2-20.png",
  "静息HFQRS(Resting HFQRS)": "/keyword-illustrations/hfqrs-ch3-01.png",
  "运动负荷HFQRS(Exercise Stress HFQRS, ES-HFQRS)": "/keyword-illustrations/hfqrs-ch3-02.png",
  "急性冠脉综合征(Acute Coronary Syndrome, ACS)": "/keyword-illustrations/hfqrs-ch3-03.png",
  "稳定性冠心病(Stable Coronary Artery Disease)": "/keyword-illustrations/hfqrs-ch3-04.png",
  "无症状心肌缺血(Silent Myocardial Ischemia)": "/keyword-illustrations/hfqrs-ch3-05.png",
  "前降支病变(LAD Lesion)": "/keyword-illustrations/hfqrs-ch3-06.png",
  "非ST段抬高ACS(NSTE-ACS)": "/keyword-illustrations/hfqrs-ch3-07.png",
  "冠脉微循环障碍(Coronary Microvascular Dysfunction, CMVD)": "/keyword-illustrations/hfqrs-ch3-08.png",
  "PCI术后评估(Post-PCI Assessment)": "/keyword-illustrations/hfqrs-ch3-09.png",
  "心梗后风险分层(Post-MI Risk Stratification)": "/keyword-illustrations/hfqrs-ch3-10.png",
  "猝死风险筛查(Sudden Death Risk Screening)": "/keyword-illustrations/hfqrs-ch3-11.png",
  "肥厚型心肌病(Hypertrophic Cardiomyopathy, HCM)": "/keyword-illustrations/hfqrs-ch3-12.png",
  "心肌病亚型鉴别(Cardiomyopathy Subtype Differentiation)": "/keyword-illustrations/hfqrs-ch3-13.png",
  "胸痛中心(Chest Pain Center)": "/keyword-illustrations/hfqrs-ch3-14.png",
  "动态随访监测(Dynamic Follow-up)": "/keyword-illustrations/hfqrs-ch3-15.png",
  "药物负荷试验(Pharmacological Stress Test)": "/keyword-illustrations/hfqrs-ch3-16.png",
  "心脏康复监测(Cardiac Rehabilitation Monitoring)": "/keyword-illustrations/hfqrs-ch3-17.png",
  "稳定性心绞痛(Stable Angina)": "/keyword-illustrations/hfqrs-ch3-18.png",
  "植入式装置(Implantable Devices)": "/keyword-illustrations/hfqrs-ch3-19.png",
  "女性冠心病诊断(CAD Diagnosis in Women)": "/keyword-illustrations/hfqrs-ch3-20.png",
};
